services:
    
    _defaults:
        autowire: true
        autoconfigure: true
    
    acme_api.event.jwt_created_listener:
        class: MarioDevment\ApiUser\Context\Users\Infrastructure\TokenManagement\CreateTokenListener
        arguments: [ '@request_stack' ]
        tags:
            - { name: kernel.event_listener, event: lexik_jwt_authentication.on_jwt_created, method: onJWTCreated }
    
    acme_api.event.jwt_decoded_listener:
        class: MarioDevment\ApiUser\Context\Users\Infrastructure\TokenManagement\ValidatingTokenListener
        arguments: [ '@request_stack' ]
        tags:
            - { name: kernel.event_listener, event: lexik_jwt_authentication.on_jwt_decoded, method: onJWTDecoded }
    
    acme_api.event.authentication_success_listener:
        class: MarioDevment\ApiUser\Context\Users\Infrastructure\TokenManagement\AuthenticationSuccessListener
        tags:
            - { name: kernel.event_listener, event: lexik_jwt_authentication.on_authentication_success, method: onAuthenticationSuccessResponse }
    
    acme_api.event.authentication_failure_listener:
        class: MarioDevment\ApiUser\Context\Users\Infrastructure\TokenManagement\AuthenticationFailureListener
        tags:
            - { name: kernel.event_listener, event: lexik_jwt_authentication.on_authentication_failure, method: onAuthenticationFailureResponse }
    
    acme_api.event.jwt_invalid_listener:
        class: MarioDevment\ApiUser\Context\Users\Infrastructure\TokenManagement\AuthenticationInvalidListener
        tags:
            - { name: kernel.event_listener, event: lexik_jwt_authentication.on_jwt_invalid, method: onJWTInvalid }
    
    acme_api.event.jwt_not_found_listener:
        class: MarioDevment\ApiUser\Context\Users\Infrastructure\TokenManagement\AuthenticationNotFoundListener
        tags:
            - { name: kernel.event_listener, event: lexik_jwt_authentication.on_jwt_not_found, method: onJWTNotFound }
    
    acme_api.event.jwt_expired_listener:
        class: App\EventListener\JWTExpiredListener
        tags:
            - { name: kernel.event_listener, event: lexik_jwt_authentication.on_jwt_expired, method: onJWTExpired }