parameters:
    env(DATABASE_URL): ''

doctrine:
    dbal:
        driver: 'pdo_mysql'
        server_version: '5.7'
        charset: utf8
        default_table_options:
            charset: utf8
            collate: utf8_unicode_ci

        url: '%env(resolve:DATABASE_URL)%'
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true
        mappings:
            MarioDevment\ApiUser:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Infrastructure/Doctrine/Entity'
                prefix: 'MarioDevment\ApiUser\Infrastructure\Doctrine\Entity'
                alias: MarioDevment\ApiUser
