monolog:
    handlers:
        console:
            type: console
            process_psr_3_messages: false
            channels: ["!event", "!doctrine", "!console"]
        filesystem:
            type: rotating_file
            formatter: Monolog\Formatter\JsonFormatter
            path: "%kernel.logs_dir%/%kernel.environment%/%kernel.environment%.json"
            level: debug
            max_files: 30
            channels: ["!event"]
