monolog:
    handlers:
        main:
            type: fingers_crossed
            action_level: error
            handler: filesystem
            excluded_404s:
                - ^/
        filesystem:
            type: rotating_file
            formatter: Monolog\Formatter\JsonFormatter
            path: "%kernel.logs_dir%/%kernel.environment%/%kernel.environment%.json"
            level: debug
            max_files: 30
        console:
            type: console
            process_psr_3_messages: false
            channels: ["!event", "!doctrine", "!external"]
        deprecation:
            type: stream
            path: "%kernel.logs_dir%/%kernel.environment%.deprecations.log"
        deprecation_filter:
            type: filter
            handler: deprecation
            max_level: info
            channels: ["php"]
