imports:
    - { resource: services/token.yaml }

parameters:

services:
   
    _defaults:
        autowire: true
        autoconfigure: true

    MarioDevment\ApiUser\:
        resource: '../src/*'
        exclude: '../src/Infrastructure/{DependencyInjection,Doctrine/Entity,Doctrine/Migrations,Tests,Symfony/Kernel.php}'

    MarioDevment\ApiUser\Infrastructure\Symfony\Controller\:
        resource: '../src/Infrastructure/Symfony/Controller'
        tags: ['controller.service_arguments']

    Monolog\Formatter\JsonFormatter:
        class: Monolog\Formatter\JsonFormatter