parameters:

services:
   
    _defaults:
        autowire: true
        autoconfigure: true

    MarioDevment\ApiUser\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'

    MarioDevment\ApiUser\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']